"""add_totp_replay_protection_fields_to_user

Revision ID: 20260312_000624
Revises: fix_delivery_logs_fk_cascade, expand_mfa_secret_column
Create Date: 2026-03-12 00:06:24.000000

This is a merge migration that combines all previous branches and adds
TOTP replay protection fields to the users table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260312_000624'
down_revision: Union[str, None] = ('fix_delivery_logs_fk_cascade', 'expand_mfa_secret_column')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_used_totp_code', sa.String(6), nullable=True))
    op.add_column('users', sa.Column('last_used_totp_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_used_totp_at')
    op.drop_column('users', 'last_used_totp_code')
    # ### end Alembic commands ###
